### ISSUE TITLE
Make the exampleSite's content more generic

### ISSUE THREAD

**Issue by bep** [forestryio/hugo-theme-novela#1]
Thanks for this great theme, much appreciated.

It would be even better if you could make the exampleSite not to be an ad for Gatsby. Gatsby is great, but isn't something that feels natural to promote on the Hugo theme site:

https://themes.gohugo.io/theme/hugo-theme-novela/

Some generic content would be better.

Thanks.

**Comment by DirtyF** [comment]
@bep agreed, it feels weird, any existing content I could use? I prefer not to replace with fake text.

**Comment by onedrawingperday** [comment]
>any existing content I could use? 

Hello @DirtyF please have a look at the content files of the [hugoBasicExample](https://github.com/gohugoio/hugoBasicExample). 

Or if you prefer simply perform a search and replace so that:
`Gatsby -becomes--> Hugo`
in the content files of the Novela exampleSite 

Once look into the above please let me know so that I can update the theme demo on the Hugo website.

Thanks.

**Comment by digitalcraftsman** [comment]
> Or if you prefer simply perform a search and replace so that:
Gatsby --becomes--> Hugo in the content files of the Novela exampleSite

That might be more confusing than beneficial. Some posts explain concepts that are specific to Gatsby and even contain JS / React code snippets, e.g. in 
https://hugo-novela-forestry.netlify.com/post/2019-04-31-understanding-the-gatsby-lifecycle/

**Comment by onedrawingperday** [comment]
Hello again @DirtyF 

Can you please look into this issue and let me know?

As mentioned above you can use content files from the [hugoBasicExample](https://github.com/gohugoio/hugoBasicExample) repo.

**Comment by onedrawingperday** [comment]
Hello again @DirtyF 

I understand that this issue may not be a priority for you.

However almost a month has passed since the original request was made about removing the Gatsby references from the theme's content files. 

As of today the Novela theme's demo and homepage links [have been disabled](https://themes.gohugo.io/hugo-theme-novela/) on the Hugo Themes website until this issue is resolved. 

So whenever you find the time to fix the content files, please notify me, so that the demo and the homepage links are restored on the Hugo Themes website.

Thank you.

**Comment by DirtyF** [comment]
> Some generic content would be better.

So now it is _mandatory_… that escalated quickly.

**Comment by onedrawingperday** [comment]
I fail to see the escalation. We made a polite request and we didn't quite get a meaningful reply or a time frame for resolution in 25 days.

Please keep communication to a minimum. We are busy people.

If you do not plan to fix the demo content then simply close this issue and I will then completely remove the theme.

Only if you issue a fix as requested above do contact me.

Thanks.

**Comment by bep** [comment]
@DirtyF I suggest Forestryio comes up with some generic content you can use in situations like these. And do remember that 1) we run Hugo and its sites on very limited resources (as in: man-hours) so we need to make it as effective as possible 2) I'm pretty sure it is in our guidelines that the content should be neutral/non-promotional. If not, I'll see to it. I suspect this would have been easier to handle if we had handled this before we merged it into the theme repo in the first place. It should be obvious to most people that we cannot be a poster stand for competing products.

**Comment by onedrawingperday** [comment]
>I'm pretty sure it is in our guidelines that the content should be neutral/non-promotional. If not, I'll see to it

@bep It used to be in the guidelines. However after we made theme demos inherit their content from the hugoBasicExample, I removed that reference months ago.

However after this incident, I have re-added the reference and expanded on it over here:
https://github.com/gohugoio/hugoThemes#example-site

So yes it is mandatory. Typically we do not see such problems with theme submissions. 
When this theme was submitted I was away. My fellow maintainer had plenty of themes to review. It's only human that the problem with this theme's content files was not spotted on time.

However that does not mean that we will keep it as-is forever on the website.

**Comment by DirtyF** [comment]
I'll see what I can do, but it's definitely not up in my priorities at the moment. Feel free to remove the theme from your directory, if it makes you less threatened by Gatsby 🤷‍♂

**Comment by regisphilibert** [comment]
Let's take a deep breath here. 

This theme is good and should remain in the directory, that being said I agree content should be generic and don't promote any brand, it being open source or not. And that all themes should follow the guidelines, that goes without saying.

I'll see if we can help @DirtyF and make the content more generic before the end of next week.

Thanks.

**Comment by onedrawingperday** [comment]
Thank you @regisphilibert 

---

@DirtyF 

For the record the Hugo team does not feel threatened by any other product. 

There is a simple rule that needs to be followed: 
We do not accept promotions of any kind on the Hugo Themes website.

**Comment by onedrawingperday** [comment]
@DirtyF 

Following the merging of #9 that addressed this issue.

The Novela theme demo was restored on the Hugo Themes website with https://github.com/gohugoio/hugoThemes/commit/5391386727b73aa303f2fd5eca00f499bbccc6ad

However note that the the Homepage button was not restored because the external demo still features the old content. 

If you want the link to the external demo re-enabled, you will also need to update the external demo's content and notify me.
